server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis?serverTimezone=UTC
    username: root
    password: 1812244d
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: chen

mybatis:
  mapper-locations: classpath*:mapper/*.xml